Repository terasolunaorg/terasoluna-gfw-web-blank, pull requests merged in 2018-09, with the labels that each got.

#363 Improve mvc:exclude-mapping Definition of interceptors in spring-mvc.xml for security #312
  src/main/resources/META-INF/spring/spring-mvc.xml
Labels: status: in-progress, type: improvement, version: 5.5.0

#372 [5.4.x]backport_Improve mvc:exclude-mapping Definition of interceptors in spring-mvc.xml for security #312
  src/main/resources/META-INF/spring/spring-mvc.xml
Labels: status: in-progress, version: 5.4.2

#373 [5.3.x]backport_Improve mvc:exclude-mapping Definition of interceptors in spring-mvc.xml for security #312
  src/main/resources/META-INF/spring/spring-mvc.xml
Labels: status: in-progress, version: 5.3.3

#376 [5.2.x]backport_Improve mvc:exclude-mapping Definition of interceptors in spring-mvc.xml for security #312
  src/main/resources/META-INF/spring/spring-mvc.xml
Labels: status: in-progress, version: 5.2.2

#374 [5.1.x]backport_Improve mvc:exclude-mapping Definition of interceptors in spring-mvc.xml for security #312
  src/main/resources/META-INF/spring/spring-mvc.xml
Labels: status: in-progress, version: 5.1.2

#375 [5.0.x]backport_Improve mvc:exclude-mapping Definition of interceptors in spring-mvc.xml for security #312
  src/main/resources/META-INF/spring/spring-mvc.xml
Labels: status: in-progress, version: 5.0.3

#378 add comment out the definition of password encoder #370
  pom.xml
  src/main/resources/META-INF/spring/applicationContext.xml
Labels: status: in-progress
