Repository terasolunaorg/terasoluna-gfw-web-blank, pull requests merged in 2019-03, with the labels that each got.

#394 apply @ByteSize #393
  src/main/resources/ValidationMessages.properties
Labels: status: in-progress, type: new-feature, version: 5.5.1

#397 update jdbc version #369
  pom.xml
Labels: status: in-progress, version: 5.5.1

#395 remove SCryptPasswordEncoder #370
  pom.xml
Labels: status: in-progress, version: 5.5.1

#398 [5.4.x] apply @ByteSize #393
  src/main/resources/ValidationMessages.properties
Labels: status: in-progress, type: new-feature, version: 5.4.2
